### PR TITLE
React v15 upgrade and fixes

### PR DESCRIPTION
**Pull request by bradchristensen**
There are a few things here - sorry for dumping them all at once but I'm interested to get your feedback anyway :smile:
- Update to React 15.x
- Update to Babel 6.x
- Reference React as a peer dependency (it turns out this was Luke's idea https://github.com/JedWatson/react-select/issues/88)
- Bundle using webpack instead of browserify (fixes usage through npm - the browserify bundle didn't seem to work for me when I was including it in my project, so I messed around with it for a while to no avail, then just packed it with webpack instead and it worked first time) :stuck_out_tongue: 
- Fix main reference in package.json to point to webpacked script (fixes usage through npm)
- Don't include React in the webpacked script (reduces bundle size)
- Remove generated files from git while retaining them in npm (standard git practice, but it does mean that you can't reference the library by its git repo any more, you can only use the npm registry - thoughts?)
- Bump to version 1.2.0 (due to republishing a couple of times as react-svg-graph-bradchristensen for testing purposes) but this should probably just be 1.1.0 for the main repo - thoughts?

### CODE REVIEW

**Comment by jwarning** [comment]
Hey man. I'm happy with most of those changes. I have been meaning to upgrade some of my OSS stuff to React 15 etc.. so it's good to see you've done it anyway. 😄  To be honest I will probably remove gulp altogether and just use webpack as it's mostly unnecessary for the majority of simple cases I find. Afaik the whole peerDependency thing is no longer a thing as of npm 3? Does it make a difference still though?

**Comment by bradchristensen** [comment]
Haha yeah, gulp does seem irrelevant these days. I haven't managed to completely get rid of it from my own projects yet though. Good to see you have jumped on the webpack bandwagon too :smile: It seems like peer dependencies are just used as hints in npm3 now, so they just throw warnings if those dependencies aren't installed. React is still installed as a dev dependency so that it can be bundled into the example app bundle though, and it has to be explicitly excluded from the webpack bundle.

**Comment by jwarning** [comment]
Cool, yeah I'll try get it merged soon. I may work on updating a couple other parts of it too and eventually adding more features when I have time haha. I'm happy to remove the generated files from git too, with the exception of the bundle for the demo site as it needs to be there.

**Comment by bradchristensen** [comment]
Ah good point, guess it will have to be if it's hosted by github. I'll fix that up tomorrow.

**Comment by jwarning** [comment]
You happy with your changes at this point? If so I'll merge and test it a bit.

**Pull request merged**
